<a href="https://colab.research.google.com/github/sateeshlevelup/MachineLearning/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
data = pd.read_csv('Advertising.csv')

data = data.rename({'Unnamed: 4':'Sales'},axis=1)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [ ]:
import pandas as pd
data = pd.read_csv('Advertising.csv')
data = data.rename({'Unnamed: 4':'Sales'},axis=1)
data.head()
data = data[['TV','sales']]
data
features = data[['TV']]
target = data[['sales']]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(features,target)
print(X_train.shape) #- input train features
print(X_test.shape)  #- #input test features
print(y_train.shape) #- #output train labels
print(y_test.shape) #-  #output test labels
from sklearn.linear_model import LinearRegression
my_model = LinearRegression()
my_model.fit(X_train, y_train)
my_model.coef_
my_model.intercept_
predictins=my_model.predict(X_test)
predictins
y_test

In [30]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, predictins)
print("Mean Squared Error (MSE):", mse)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)


Mean Squared Error (MSE): 13.383433424876815
Root Mean Squared Error (RMSE): 3.6583375220005077


In [ ]:
import matplotlib.pyplot as plt

# Plotting the actual data points
plt.scatter(X_test, y_test, color='blue', label='Actual data')

# Plotting the regression line
plt.plot(X_test, predictins, color='red', label='Regression line')

# Adding labels and title
plt.xlabel('TV advertising expenditure')
plt.ylabel('Sales')
plt.title('Linear Regression: TV advertising vs. Sales')

# Adding legend
plt.legend()

# Displaying the plot
plt.show()


In [24]:
# Define a new data point
new_data_point = [[240]]  # Assuming 100 units of TV advertising expenditure

# Make predictions using the new data point
predicted_sales = my_model.predict(new_data_point)

# Print the predicted sales
print("Predicted sales:", predicted_sales)


Predicted sales: [[18.23696306]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
data = pd.read_csv('Advertising.csv')
data = data.rename({'Unnamed: 4':'Sales'},axis=1)
data.head()

# New section

In [ ]:
data = data[['TV','sales']]
data

In [5]:
features = data[['TV']]
target = data[['sales']]

In [6]:
# split the data

from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train,y_test = train_test_split(features,target)

In [8]:
print(X_train.shape) #- input train features
print(X_test.shape)  #- #input test features
print(y_train.shape) #- #output train labels
print(y_test.shape) #-  #output test labels

(150, 1)
(50, 1)
(150, 1)
(50, 1)


In [9]:
#2. Build a model on training data

from sklearn.linear_model import LinearRegression


In [10]:
my_model = LinearRegression()

In [11]:
my_model.fit(X_train, y_train)

LinearRegression()

In [12]:
my_model.coef_

array([[0.04657374]])

In [13]:
my_model.intercept_

array([7.2065515])

In [14]:
#test my model on test data
predictins=my_model.predict(X_test)

In [ ]:
predictins

In [ ]:
y_test

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mean_squared_error(y_test,predictins)

12.028235266313116

In [ ]:
features = data[['TV', 'radio', 'newspaper']]
target = data[['sales']]

In [ ]:
#1. Split the data

from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [ ]:
print(X_train.shape) #- input train features
print(X_test.shape)  #- #input test features
print(y_train.shape) #- #output train labels
print(y_test.shape) #-  #output test labels

(150, 3)
(50, 3)
(150, 1)
(50, 1)


In [ ]:
#2. Build a model on training data

from sklearn.linear_model import LinearRegression

In [ ]:
my_model = LinearRegression()

In [ ]:
my_model.fit(X_train, y_train)

LinearRegression()

In [ ]:
my_model.coef_

array([[0.04406492, 0.18874002, 0.00828679]])

In [ ]:
my_model.intercept_

array([2.94683046])

In [ ]:
#3. Test my model on test data

predictions = my_model.predict(X_test)

In [ ]:
predictions

In [ ]:
y_test

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test, predictions)

3.2096082757168114

In [ ]:
Slope and intercept for TV vs Sales - m1, c1
Slope and intercept for radio vs Sales - m2, c2
Slope and intercept for newspaper vs Sales - m3, c3


SyntaxError: invalid syntax (<ipython-input-45-f38bbb5f0fd7>, line 1)